version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - default

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    networks:
      - default

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - default

networks:
  default:
    driver: bridge
